server:
  port: 8003


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml      # mybatis配置文件所在路径
  type-aliases-package: com.ydss.api.entities  # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

spring:
   application:
    name: abc
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型              # mysql驱动包
    driver-class-name: com.mysql.jdbc.Driver                                 # 等待连接获取的最大超时时间
    url: jdbc:mysql://localhost:3306/clouddb02        # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200
eureka:
  instance:
    instance-id: microservicecloud-provider-dept-8002
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/

